export enum Tab {
    Sounds = "sounds",
    Rows = "rows",
    Actions = "actions",
    Decorations = "decorations",
    Rooms = "rooms",
    Windows = "windows",
    Unknown = "unknown",
}
export enum SayReadyGetSetGoWords {
    SayReaDyGetSetGoNew = "SayReaDyGetSetGoNew",
    SayReaDyGetSetOne = "SayReaDyGetSetOne",
    SayGetSetGo = "SayGetSetGo",
    SayGetSetOne = "SayGetSetOne",
    JustSayRea = "JustSayRea",
    JustSayDy = "JustSayDy",
    JustSayGet = "JustSayGet",
    JustSaySet = "JustSaySet",
    JustSayAnd = "JustSayAnd",
    JustSayGo = "JustSayGo",
    JustSayStop = "JustSayStop",
    JustSayAndStop = "JustSayAndStop",
    SaySwitch = "SaySwitch",
    SayWatch = "SayWatch",
    SayListen = "SayListen",
    Count1 = "Count1",
    Count2 = "Count2",
    Count3 = "Count3",
    Count4 = "Count4",
    Count5 = "Count5",
    Count6 = "Count6",
    Count7 = "Count7",
    Count8 = "Count8",
    Count9 = "Count9",
    Count10 = "Count10",
    SayReadyGetSetGo = "SayReadyGetSetGo",
    JustSayReady = "JustSayReady",
}
export enum EventType {
    AddClassicBeat = "AddClassicBeat",
    AddFreeTimeBeat = "AddFreeTimeBeat",
    AddOneshotBeat = "AddOneshotBeat",
    AdvanceText = "AdvanceText",
    BassDrop = "BassDrop",
    Blend = "Blend",
    CallCustomMethod = "CallCustomMethod",
    ChangeCharacter = "ChangeCharacter",
    ChangePlayersRows = "ChangePlayersRows",
    Comment = "Comment",
    CustomFlash = "CustomFlash",
    DesktopColor = "DesktopColor",
    FadeRoom = "FadeRoom",
    FinishLevel = "FinishLevel",
    Flash = "Flash",
    FlipScreen = "FlipScreen",
    FloatingText = "FloatingText",
    ForwardDecorationEvent = "ForwardDecorationEvent",
    ForwardEvent = "ForwardEvent",
    ForwardRowEvent = "ForwardRowEvent",
    HideRow = "HideRow",
    HideWindow = "HideWindow",
    InvertColors = "InvertColors",
    MacroEvent = "MacroEvent",
    MaskRoom = "MaskRoom",
    Move = "Move",
    MoveCamera = "MoveCamera",
    MoveRoom = "MoveRoom",
    MoveRow = "MoveRow",
    NarrateRowInfo = "NarrateRowInfo",
    NewWindowDance = "NewWindowDance",
    PaintHands = "PaintHands",
    PlayAnimation = "PlayAnimation",
    PlayExpression = "PlayExpression",
    PlaySong = "PlaySong",
    PlaySound = "PlaySound",
    PulseCamera = "PulseCamera",
    PulseFreeTimeBeat = "PulseFreeTimeBeat",
    ReadNarration = "ReadNarration",
    RenameWindow = "RenameWindow",
    ReorderRooms = "ReorderRooms",
    ReorderRow = "ReorderRow",
    ReorderSprite = "ReorderSprite",
    ReorderWindows = "ReorderWindows",
    SayReadyGetSetGo = "SayReadyGetSetGo",
    SetBackgroundColor = "SetBackgroundColor",
    SetBeatSound = "SetBeatSound",
    SetBeatsPerMinute = "SetBeatsPerMinute",
    SetClapSounds = "SetClapSounds",
    SetCountingSound = "SetCountingSound",
    SetCrotchetsPerBar = "SetCrotchetsPerBar",
    SetForeground = "SetForeground",
    SetGameSound = "SetGameSound",
    SetHandOwner = "SetHandOwner",
    SetHeartExplodeInterval = "SetHeartExplodeInterval",
    SetHeartExplodeVolume = "SetHeartExplodeVolume",
    SetMainWindow = "SetMainWindow",
    SetOneshotWave = "SetOneshotWave",
    SetPlayStyle = "SetPlayStyle",
    SetRoomContentMode = "SetRoomContentMode",
    SetRoomPerspective = "SetRoomPerspective",
    SetRowXs = "SetRowXs",
    SetSpeed = "SetSpeed",
    SetTheme = "SetTheme",
    SetVFXPreset = "SetVFXPreset",
    SetVisible = "SetVisible",
    SetWindowContent = "SetWindowContent",
    ShakeScreen = "ShakeScreen",
    ShakeScreenCustom = "ShakeScreenCustom",
    ShowDialogue = "ShowDialogue",
    ShowHands = "ShowHands",
    ShowRooms = "ShowRooms",
    ShowStatusSign = "ShowStatusSign",
    ShowSubdivisionsRows = "ShowSubdivisionsRows",
    SpinningRows = "SpinningRows",
    Stutter = "Stutter",
    TagAction = "TagAction",
    TextExplosion = "TextExplosion",
    Tile = "Tile",
    Tint = "Tint",
    TintRows = "TintRows",
    WindowResize = "WindowResize",
}
export enum EventAttriblte {
    None = 0,
    DurationEvent = 0b001,
    RoomEvent = 0b010,
}
class EventInfo {
    public readonly defaultTab: Tab;
    public readonly durationKey: string = "duration";
    private readonly attr: EventAttriblte;
    public get isDurationEvent(): boolean {
        return (this.attr & EventAttriblte.DurationEvent) !== 0;
    }
    public get isRoomEvent(): boolean {
        return (this.attr & EventAttriblte.RoomEvent) !== 0;
    }
    constructor(tab: Tab);
    constructor(tab: Tab, enumAttriblte: EventAttriblte);
    constructor(tab: Tab, enumAttriblte: EventAttriblte, durationKey: string);
    constructor(tab: Tab, enumAttriblte?: EventAttriblte, durationKey?: string) {
        this.defaultTab = tab;
        this.attr = enumAttriblte ?? EventAttriblte.None;
        if (durationKey !== undefined) {
            this.durationKey = durationKey;
        }
    }
}
class WordInfo{
    public readonly phrase: string;
    public readonly length: number;
    constructor(phrase: string, length: number) {
        this.phrase = phrase;
        this.length = length;
    }
}
export const WordInfos: Record<SayReadyGetSetGoWords, WordInfo> = {
    SayReaDyGetSetGoNew: new WordInfo("Rea, Dy, Get, Set, Go!", 4),
    SayReaDyGetSetOne: new WordInfo("Rea, Dy, Get, Set, One!", 4),
    SayGetSetGo: new WordInfo("Get, Set, Go!", 2),
    SayGetSetOne: new WordInfo("Get, Set, One!", 2),
    JustSayRea: new WordInfo("Rea", 0),
    JustSayDy: new WordInfo("Dy", 0),
    JustSayGet: new WordInfo("Get", 0),
    JustSaySet: new WordInfo("Set", 0),
    JustSayAnd: new WordInfo("And", 0),
    JustSayGo: new WordInfo("Go!", 0),
    JustSayStop: new WordInfo("Stop", 0),
    JustSayAndStop: new WordInfo("And Stop!", 0),
    SaySwitch: new WordInfo("Switch", 0),
    SayWatch: new WordInfo("Watch", 0),
    SayListen: new WordInfo("Listen", 0),
    Count1: new WordInfo("1", 0),
    Count2: new WordInfo("2", 0),
    Count3: new WordInfo("3", 0),
    Count4: new WordInfo("4", 0),
    Count5: new WordInfo("5", 0),
    Count6: new WordInfo("6", 0),
    Count7: new WordInfo("7", 0),
    Count8: new WordInfo("8", 0),
    Count9: new WordInfo("9", 0),
    Count10: new WordInfo("10", 0),
    SayReadyGetSetGo: new WordInfo("Ready, Get, Set, Go!", 4),
    JustSayReady: new WordInfo("Ready", 0),
}
export const EventInfos: Record<EventType, EventInfo> = {
    AddClassicBeat: new EventInfo(Tab.Rows),
    AddFreeTimeBeat: new EventInfo(Tab.Rows),
    AddOneshotBeat: new EventInfo(Tab.Rows),
    AdvanceText: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    BassDrop: new EventInfo(Tab.Actions),
    Blend: new EventInfo(Tab.Decorations),
    CallCustomMethod: new EventInfo(Tab.Actions),
    ChangeCharacter: new EventInfo(Tab.Actions),
    ChangePlayersRows: new EventInfo(Tab.Actions),
    Comment: new EventInfo(Tab.Unknown),
    CustomFlash: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    DesktopColor: new EventInfo(Tab.Windows, EventAttriblte.DurationEvent),
    FadeRoom: new EventInfo(Tab.Rooms, EventAttriblte.DurationEvent),
    FinishLevel: new EventInfo(Tab.Actions),
    Flash: new EventInfo(Tab.Actions),
    FlipScreen: new EventInfo(Tab.Actions),
    FloatingText: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    ForwardDecorationEvent: new EventInfo(Tab.Decorations),
    ForwardEvent: new EventInfo(Tab.Unknown),
    ForwardRowEvent: new EventInfo(Tab.Rows),
    HideRow: new EventInfo(Tab.Actions),
    HideWindow: new EventInfo(Tab.Windows),
    InvertColors: new EventInfo(Tab.Actions),
    MacroEvent: new EventInfo(Tab.Unknown),
    MaskRoom: new EventInfo(Tab.Rooms),
    Move: new EventInfo(Tab.Decorations, EventAttriblte.DurationEvent),
    MoveCamera: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    MoveRoom: new EventInfo(Tab.Rooms, EventAttriblte.DurationEvent),
    MoveRow: new EventInfo(Tab.Rows, EventAttriblte.DurationEvent),
    NarrateRowInfo: new EventInfo(Tab.Sounds),
    NewWindowDance: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    PaintHands: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    PlayAnimation: new EventInfo(Tab.Decorations),
    PlayExpression: new EventInfo(Tab.Actions),
    PlaySong: new EventInfo(Tab.Sounds),
    PlaySound: new EventInfo(Tab.Sounds),
    PulseCamera: new EventInfo(Tab.Actions),
    PulseFreeTimeBeat: new EventInfo(Tab.Rows),
    ReadNarration: new EventInfo(Tab.Sounds),
    RenameWindow: new EventInfo(Tab.Windows),
    ReorderRooms: new EventInfo(Tab.Rooms),
    ReorderRow: new EventInfo(Tab.Rows),
    ReorderSprite: new EventInfo(Tab.Decorations),
    ReorderWindows: new EventInfo(Tab.Windows),
    SayReadyGetSetGo: new EventInfo(Tab.Sounds),
    SetBackgroundColor: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    SetBeatSound: new EventInfo(Tab.Sounds),
    SetBeatsPerMinute: new EventInfo(Tab.Sounds),
    SetClapSounds: new EventInfo(Tab.Sounds),
    SetCountingSound: new EventInfo(Tab.Sounds),
    SetCrotchetsPerBar: new EventInfo(Tab.Sounds),
    SetForeground: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    SetGameSound: new EventInfo(Tab.Sounds),
    SetHandOwner: new EventInfo(Tab.Actions),
    SetHeartExplodeInterval: new EventInfo(Tab.Sounds),
    SetHeartExplodeVolume: new EventInfo(Tab.Sounds),
    SetMainWindow: new EventInfo(Tab.Windows),
    SetOneshotWave: new EventInfo(Tab.Rows),
    SetPlayStyle: new EventInfo(Tab.Actions),
    SetRoomContentMode: new EventInfo(Tab.Rooms),
    SetRoomPerspective: new EventInfo(Tab.Rooms, EventAttriblte.DurationEvent),
    SetRowXs: new EventInfo(Tab.Rows),
    SetSpeed: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    SetTheme: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    SetVFXPreset: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    SetVisible: new EventInfo(Tab.Decorations),
    SetWindowContent: new EventInfo(Tab.Windows, EventAttriblte.DurationEvent),
    ShakeScreen: new EventInfo(Tab.Actions),
    ShakeScreenCustom: new EventInfo(
        Tab.Actions,
        EventAttriblte.DurationEvent,
    ),
    ShowDialogue: new EventInfo(Tab.Actions),
    ShowHands: new EventInfo(Tab.Actions),
    ShowRooms: new EventInfo(Tab.Rooms, EventAttriblte.DurationEvent),
    ShowStatusSign: new EventInfo(
        Tab.Actions,
        EventAttriblte.DurationEvent,
    ),
    ShowSubdivisionsRows: new EventInfo(Tab.Actions),
    SpinningRows: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    Stutter: new EventInfo(Tab.Actions),
    TagAction: new EventInfo(Tab.Actions),
    TextExplosion: new EventInfo(Tab.Actions),
    Tile: new EventInfo(Tab.Decorations, EventAttriblte.DurationEvent),
    Tint: new EventInfo(Tab.Decorations, EventAttriblte.DurationEvent),
    TintRows: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
    WindowResize: new EventInfo(Tab.Actions, EventAttriblte.DurationEvent),
};
